spring.application.name=ai-release-notes
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_release_notes_db
spring.datasource.username=postgres
spring.datasource.password=User@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true